safe:             false
port:             7998
baseurl:          /Font-Awesome/  # Where GitHub serves the project up from
url:              http://localhost:7998

source:           src
destination:      _gh_pages
plugins:          src/_plugins

pygments:         true
permalink:        pretty

# ensures SCSS files are compiled
include:          [_bordered-pulled.scss, _core.scss, _fixed-width.scss, _icons.scss, _larger.scss, _list.scss, _mixins.scss, _path.scss, _rotated-flipped.scss, _spinning.scss, _stacked.scss, _variables.scss]

# used in building icon pages
icon_meta:        src/icons.yml
icon_layout:      icon.html    # Relative to _layouts directory
icon_destination: icon         # Relative to destination

fontawesome:
  version:        4.1.0
  minor_version:  4.1
  url:            http://fontawesome.io
  legacy_url:     http://fortawesome.github.com/Font-Awesome/
  blog_url:       http://blog.fontawesome.io
  twitter:        fontawesome
  tagline:        The iconic font and CSS framework
  css_prefix:     fa
  author:
    name:         Dave Gandy
    email:        dave@fontawesome.io
    twitter:      davegandy
  github:
    url:          https://github.com/FortAwesome/Font-Awesome
    project:      Font-Awesome
    org:          FortAwesome
  license:
    font:
      version:      SIL OFL 1.1
      url:          http://scripts.sil.org/OFL
    code:
      version:      MIT License
      url:          http://opensource.org/licenses/mit-license.html
    documentation:
      version:      CC BY 3.0
      url:          http://creativecommons.org/licenses/by/3.0/

bootstrap:
  version:        3.1.1
  url:            http://getbootstrap.com

jquery:
  version:        1.11.0
